// <auto-generated />
using System;
using Gotlandsrussen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gotlandsrussen.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20250514200112_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gotlandsrussen.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BookedFromDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BookedToDate")
                        .HasColumnType("date");

                    b.Property<bool>("BookingIsCancelled")
                        .HasColumnType("boolean");

                    b.Property<int>("GuestId")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfAdults")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedFromDate = new DateOnly(2025, 6, 10),
                            BookedToDate = new DateOnly(2025, 6, 15),
                            BookingIsCancelled = false,
                            GuestId = 1,
                            NumberOfAdults = 2,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 2,
                            BookedFromDate = new DateOnly(2025, 7, 1),
                            BookedToDate = new DateOnly(2025, 7, 5),
                            BookingIsCancelled = false,
                            GuestId = 2,
                            NumberOfAdults = 2,
                            NumberOfChildren = 2
                        },
                        new
                        {
                            Id = 3,
                            BookedFromDate = new DateOnly(2025, 8, 20),
                            BookedToDate = new DateOnly(2025, 8, 25),
                            BookingIsCancelled = true,
                            GuestId = 3,
                            NumberOfAdults = 1,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 4,
                            BookedFromDate = new DateOnly(2025, 9, 5),
                            BookedToDate = new DateOnly(2025, 9, 10),
                            BookingIsCancelled = false,
                            GuestId = 4,
                            NumberOfAdults = 2,
                            NumberOfChildren = 1
                        },
                        new
                        {
                            Id = 5,
                            BookedFromDate = new DateOnly(2025, 10, 15),
                            BookedToDate = new DateOnly(2025, 10, 18),
                            BookingIsCancelled = false,
                            GuestId = 5,
                            NumberOfAdults = 1,
                            NumberOfChildren = 1
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.BookingRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("BookingRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 2,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 3,
                            RoomId = 4
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 4,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 5,
                            RoomId = 5
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.BreakfastOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("BreakfastOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            IsIncluded = true
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 2,
                            IsIncluded = false
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 3,
                            IsIncluded = true
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 4,
                            IsIncluded = false
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 5,
                            IsIncluded = true
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Andersson",
                            Phone = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Bengtsson",
                            Phone = "0702345678"
                        },
                        new
                        {
                            Id = 3,
                            Email = "tom@example.com",
                            FirstName = "Tom",
                            LastName = "Larsson",
                            Phone = "0702345679"
                        },
                        new
                        {
                            Id = 4,
                            Email = "lisa@example.com",
                            FirstName = "Lisa",
                            LastName = "Helgesson",
                            Phone = "0702345680"
                        },
                        new
                        {
                            Id = 5,
                            Email = "kalle@example.com",
                            FirstName = "Kalle",
                            LastName = "Spongtsson",
                            Phone = "0702345681"
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomName = "101",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoomName = "102",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoomName = "103",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoomName = "104",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            RoomName = "105",
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single",
                            NumberOfBeds = 1,
                            PricePerNight = 500m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Double",
                            NumberOfBeds = 2,
                            PricePerNight = 900m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Family",
                            NumberOfBeds = 4,
                            PricePerNight = 1500m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Suite",
                            NumberOfBeds = 6,
                            PricePerNight = 3000m
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Booking", b =>
                {
                    b.HasOne("Gotlandsrussen.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.BookingRoom", b =>
                {
                    b.HasOne("Gotlandsrussen.Models.Booking", "Booking")
                        .WithMany("BookingRooms")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gotlandsrussen.Models.Room", "Room")
                        .WithMany("BookingRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.BreakfastOption", b =>
                {
                    b.HasOne("Gotlandsrussen.Models.Booking", "Booking")
                        .WithOne("BreakfastOption")
                        .HasForeignKey("Gotlandsrussen.Models.BreakfastOption", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Room", b =>
                {
                    b.HasOne("Gotlandsrussen.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Booking", b =>
                {
                    b.Navigation("BookingRooms");

                    b.Navigation("BreakfastOption");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Room", b =>
                {
                    b.Navigation("BookingRooms");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
