// <auto-generated />
using System;
using Gotlandsrussen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gotlandsrussen.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gotlandsrussen.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BookedFromDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BookedToDate")
                        .HasColumnType("date");

                    b.Property<bool>("BookingIsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("Breakfast")
                        .HasColumnType("boolean");

                    b.Property<int>("GuestId")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfAdults")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedFromDate = new DateOnly(2025, 6, 10),
                            BookedToDate = new DateOnly(2025, 6, 11),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 1,
                            NumberOfAdults = 1,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 2,
                            BookedFromDate = new DateOnly(2025, 6, 10),
                            BookedToDate = new DateOnly(2025, 6, 15),
                            BookingIsCancelled = false,
                            Breakfast = true,
                            GuestId = 2,
                            NumberOfAdults = 1,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 3,
                            BookedFromDate = new DateOnly(2025, 6, 11),
                            BookedToDate = new DateOnly(2025, 6, 13),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 3,
                            NumberOfAdults = 1,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 4,
                            BookedFromDate = new DateOnly(2025, 6, 12),
                            BookedToDate = new DateOnly(2025, 6, 13),
                            BookingIsCancelled = false,
                            Breakfast = true,
                            GuestId = 4,
                            NumberOfAdults = 2,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 5,
                            BookedFromDate = new DateOnly(2025, 6, 15),
                            BookedToDate = new DateOnly(2025, 6, 17),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 5,
                            NumberOfAdults = 2,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 6,
                            BookedFromDate = new DateOnly(2025, 6, 15),
                            BookedToDate = new DateOnly(2025, 6, 16),
                            BookingIsCancelled = false,
                            Breakfast = true,
                            GuestId = 6,
                            NumberOfAdults = 2,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 7,
                            BookedFromDate = new DateOnly(2025, 6, 16),
                            BookedToDate = new DateOnly(2025, 6, 18),
                            BookingIsCancelled = false,
                            Breakfast = true,
                            GuestId = 7,
                            NumberOfAdults = 2,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 8,
                            BookedFromDate = new DateOnly(2025, 7, 1),
                            BookedToDate = new DateOnly(2025, 7, 2),
                            BookingIsCancelled = false,
                            Breakfast = true,
                            GuestId = 8,
                            NumberOfAdults = 2,
                            NumberOfChildren = 2
                        },
                        new
                        {
                            Id = 9,
                            BookedFromDate = new DateOnly(2025, 7, 1),
                            BookedToDate = new DateOnly(2025, 7, 3),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 9,
                            NumberOfAdults = 2,
                            NumberOfChildren = 1
                        },
                        new
                        {
                            Id = 10,
                            BookedFromDate = new DateOnly(2025, 7, 1),
                            BookedToDate = new DateOnly(2025, 7, 5),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 10,
                            NumberOfAdults = 2,
                            NumberOfChildren = 2
                        },
                        new
                        {
                            Id = 11,
                            BookedFromDate = new DateOnly(2025, 7, 5),
                            BookedToDate = new DateOnly(2025, 7, 8),
                            BookingIsCancelled = false,
                            Breakfast = true,
                            GuestId = 11,
                            NumberOfAdults = 2,
                            NumberOfChildren = 2
                        },
                        new
                        {
                            Id = 12,
                            BookedFromDate = new DateOnly(2025, 7, 10),
                            BookedToDate = new DateOnly(2025, 7, 15),
                            BookingIsCancelled = false,
                            Breakfast = true,
                            GuestId = 12,
                            NumberOfAdults = 2,
                            NumberOfChildren = 1
                        },
                        new
                        {
                            Id = 13,
                            BookedFromDate = new DateOnly(2025, 7, 17),
                            BookedToDate = new DateOnly(2025, 7, 19),
                            BookingIsCancelled = false,
                            Breakfast = true,
                            GuestId = 13,
                            NumberOfAdults = 2,
                            NumberOfChildren = 2
                        },
                        new
                        {
                            Id = 14,
                            BookedFromDate = new DateOnly(2025, 7, 25),
                            BookedToDate = new DateOnly(2025, 7, 26),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 14,
                            NumberOfAdults = 2,
                            NumberOfChildren = 3
                        },
                        new
                        {
                            Id = 15,
                            BookedFromDate = new DateOnly(2025, 8, 2),
                            BookedToDate = new DateOnly(2025, 8, 3),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 15,
                            NumberOfAdults = 2,
                            NumberOfChildren = 4
                        },
                        new
                        {
                            Id = 16,
                            BookedFromDate = new DateOnly(2025, 8, 3),
                            BookedToDate = new DateOnly(2025, 8, 5),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 1,
                            NumberOfAdults = 2,
                            NumberOfChildren = 4
                        },
                        new
                        {
                            Id = 17,
                            BookedFromDate = new DateOnly(2025, 8, 5),
                            BookedToDate = new DateOnly(2025, 8, 7),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 2,
                            NumberOfAdults = 4,
                            NumberOfChildren = 0
                        },
                        new
                        {
                            Id = 18,
                            BookedFromDate = new DateOnly(2025, 8, 10),
                            BookedToDate = new DateOnly(2025, 8, 13),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 3,
                            NumberOfAdults = 3,
                            NumberOfChildren = 3
                        },
                        new
                        {
                            Id = 19,
                            BookedFromDate = new DateOnly(2025, 8, 12),
                            BookedToDate = new DateOnly(2025, 8, 13),
                            BookingIsCancelled = false,
                            Breakfast = false,
                            GuestId = 4,
                            NumberOfAdults = 4,
                            NumberOfChildren = 8
                        },
                        new
                        {
                            Id = 20,
                            BookedFromDate = new DateOnly(2025, 8, 15),
                            BookedToDate = new DateOnly(2025, 8, 20),
                            BookingIsCancelled = false,
                            Breakfast = true,
                            GuestId = 5,
                            NumberOfAdults = 2,
                            NumberOfChildren = 5
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.BookingRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("BookingRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 2,
                            RoomId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 3,
                            RoomId = 3
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 4,
                            RoomId = 6
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 5,
                            RoomId = 7
                        },
                        new
                        {
                            Id = 6,
                            BookingId = 6,
                            RoomId = 8
                        },
                        new
                        {
                            Id = 7,
                            BookingId = 7,
                            RoomId = 9
                        },
                        new
                        {
                            Id = 8,
                            BookingId = 8,
                            RoomId = 11
                        },
                        new
                        {
                            Id = 9,
                            BookingId = 9,
                            RoomId = 12
                        },
                        new
                        {
                            Id = 10,
                            BookingId = 10,
                            RoomId = 13
                        },
                        new
                        {
                            Id = 11,
                            BookingId = 11,
                            RoomId = 14
                        },
                        new
                        {
                            Id = 12,
                            BookingId = 12,
                            RoomId = 15
                        },
                        new
                        {
                            Id = 13,
                            BookingId = 13,
                            RoomId = 16
                        },
                        new
                        {
                            Id = 14,
                            BookingId = 14,
                            RoomId = 21
                        },
                        new
                        {
                            Id = 15,
                            BookingId = 15,
                            RoomId = 22
                        },
                        new
                        {
                            Id = 16,
                            BookingId = 16,
                            RoomId = 23
                        },
                        new
                        {
                            Id = 17,
                            BookingId = 17,
                            RoomId = 24
                        },
                        new
                        {
                            Id = 18,
                            BookingId = 18,
                            RoomId = 21
                        },
                        new
                        {
                            Id = 19,
                            BookingId = 19,
                            RoomId = 25
                        },
                        new
                        {
                            Id = 20,
                            BookingId = 20,
                            RoomId = 25
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Andersson",
                            Phone = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Bengtsson",
                            Phone = "0702345678"
                        },
                        new
                        {
                            Id = 3,
                            Email = "tom@example.com",
                            FirstName = "Tom",
                            LastName = "Larsson",
                            Phone = "0702345679"
                        },
                        new
                        {
                            Id = 4,
                            Email = "lisa@example.com",
                            FirstName = "Lisa",
                            LastName = "Helgesson",
                            Phone = "0702345680"
                        },
                        new
                        {
                            Id = 5,
                            Email = "kalle@example.com",
                            FirstName = "Kalle",
                            LastName = "Spongtsson",
                            Phone = "0702345681"
                        },
                        new
                        {
                            Id = 6,
                            Email = "emma@example.com",
                            FirstName = "Emma",
                            LastName = "Nilsson",
                            Phone = "0702345682"
                        },
                        new
                        {
                            Id = 7,
                            Email = "oscar@example.com",
                            FirstName = "Oscar",
                            LastName = "Johansson",
                            Phone = "0702345683"
                        },
                        new
                        {
                            Id = 8,
                            Email = "sara@example.com",
                            FirstName = "Sara",
                            LastName = "Karlsson",
                            Phone = "0702345684"
                        },
                        new
                        {
                            Id = 9,
                            Email = "erik@example.com",
                            FirstName = "Erik",
                            LastName = "Svensson",
                            Phone = "0702345685"
                        },
                        new
                        {
                            Id = 10,
                            Email = "maja@example.com",
                            FirstName = "Maja",
                            LastName = "Gustafsson",
                            Phone = "0702345686"
                        },
                        new
                        {
                            Id = 11,
                            Email = "johan@example.com",
                            FirstName = "Johan",
                            LastName = "Lindberg",
                            Phone = "0702345687"
                        },
                        new
                        {
                            Id = 12,
                            Email = "elin@example.com",
                            FirstName = "Elin",
                            LastName = "Persson",
                            Phone = "0702345688"
                        },
                        new
                        {
                            Id = 13,
                            Email = "andreas@example.com",
                            FirstName = "Andreas",
                            LastName = "Eriksson",
                            Phone = "0702345689"
                        },
                        new
                        {
                            Id = 14,
                            Email = "nora@example.com",
                            FirstName = "Nora",
                            LastName = "Bergström",
                            Phone = "0702345690"
                        },
                        new
                        {
                            Id = 15,
                            Email = "viktor@example.com",
                            FirstName = "Viktor",
                            LastName = "Holm",
                            Phone = "0702345691"
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomName = "101",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoomName = "102",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            RoomName = "103",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            RoomName = "104",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            RoomName = "105",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            RoomName = "106",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            RoomName = "107",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            RoomName = "108",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            RoomName = "109",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            RoomName = "110",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            RoomName = "111",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            RoomName = "112",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            RoomName = "113",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            RoomName = "114",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            RoomName = "115",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            RoomName = "116",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            RoomName = "117",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 18,
                            RoomName = "118",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 19,
                            RoomName = "119",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 20,
                            RoomName = "120",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 21,
                            RoomName = "121",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 22,
                            RoomName = "122",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 23,
                            RoomName = "123",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 24,
                            RoomName = "124",
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 25,
                            RoomName = "125",
                            RoomTypeId = 5
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfBeds")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single",
                            NumberOfBeds = 1,
                            PricePerNight = 500m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Double",
                            NumberOfBeds = 2,
                            PricePerNight = 900m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Family",
                            NumberOfBeds = 4,
                            PricePerNight = 1500m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Suite",
                            NumberOfBeds = 6,
                            PricePerNight = 3000m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stables",
                            NumberOfBeds = 12,
                            PricePerNight = 5500m
                        });
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Booking", b =>
                {
                    b.HasOne("Gotlandsrussen.Models.Guest", "Guest")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.BookingRoom", b =>
                {
                    b.HasOne("Gotlandsrussen.Models.Booking", "Booking")
                        .WithMany("BookingRooms")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gotlandsrussen.Models.Room", "Room")
                        .WithMany("BookingRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Room", b =>
                {
                    b.HasOne("Gotlandsrussen.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Booking", b =>
                {
                    b.Navigation("BookingRooms");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Guest", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.Room", b =>
                {
                    b.Navigation("BookingRooms");
                });

            modelBuilder.Entity("Gotlandsrussen.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
